### PR TITLE
Use Redux Thunk to handle API requests

### PR DESCRIPTION
**Pull request by highskillmasters-admin**
Use Redux Thunk to handle API requests for `auth` and `members`.

### CODE REVIEW

**Comment by highskillmasters-admin** [comment]
@mhaidarh Whoa, tons of updates! Thank you.

**Review by mhaidarhanif — APPROVED** [review]
All good here. Should be working well.

**Comment by highskillmasters-admin** [comment]
@mhaidarh Had to deploy the latest API first.

**Comment by highskillmasters-admin** [comment]
The latest API has been deployed.

**Pull request merged**
